---
 title: "Data Mugging"
author: "Willa Van Liew"
date: "2023-07-09"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
library(fastDummies)
games <- import("../MLModels/currentModel/Final.csv")
pub_dev <- import("../DataVisualization/CurrentVisualization/cleanPubDev.csv")
pub_dev
```

### Publishers Cleaning 
```{r}
games %>%
  mutate(pub_Nintendo = str_detect(publishers, "Nintendo"),
         pub_Ubisoft = str_detect(publishers, "Ubisoft"),
         pub_Sony = str_detect(publishers, "Sony"),
         pub_Activision = str_detect(publishers, "Activision"),
         pub_EA = str_detect(publishers, "EA"),
         pub_namco = str_detect(publishers, "Namco"),
         pub_konami = str_detect(publishers, "Konami"),
         pub_koei = str_detect(publishers, "Koei"),
         pub_sega = str_detect(publishers, "Sega"),
         pub_capcom = str_detect(publishers, "Capcom"),
         pub_rockstar = str_detect(publishers, "Rockstar"),
         pub_THQ = str_detect(publishers, "THQ"),
         pub_2K = str_detect(publishers, "2K"),
         pub_D3 = str_detect(publishers, "D3"),
         pub_vivendi = str_detect(publishers, "Vivendi"),
         pub_majesco = str_detect(publishers, "Majesco"),
         pub_microsoft = str_detect(publishers, "Microsoft"),
         pub_SquareEnix = str_detect(publishers, "SquareEnix"),
         pub_505 = str_detect(publishers, "505 Games"),
         pub_Atari = str_detect(publishers, "Atari"),
         pub_Spike = str_detect(publishers, "Spike"),
         pub_RisingStar = str_detect(publishers, "Rising Star"),
         pub_Midway = str_detect(publishers, "Midway"),
         pub_Spike = str_detect(publishers, "LucasArts"),
         pub_Eidos = str_detect(publishers, "Eidos"),
         pub_WarnerBros = str_detect(publishers, "Warner Bros"),
         pub_Atlus = str_detect(publishers, "Atlus"),
         pub_Codemasters = str_detect(publishers, "Codemasters"),
         pub_Disney = str_detect(publishers, "Disney"),
        pub_count = str_count(publishers, ",") + 1,
        pub_other = publishers %in% c("Marvelous","The Adventure Company", "Conspiracy Entertainment","ZOO Digital","Zoo", "Bethesda",
                                             "Crave", "Gameloft","Aksys","Brash","Red Mile Entertainment","Oxygen Games","Sierra Entertainment",
                                             "Noise Factory","Idea Factory","Digital Entertainment Pool", "System 3","Sandlot Games","Destineer",
                                            "Funbox Media", "Virgin Play","V.2 Play","RTL Games", "Nippon Ichi Software", "MumboJumbo", "SNK",
                                            "Valve", "Disney Interactive Studios", "TopWare Interactive","PlayFirst", "Mindscape", "MTV Games",
                                            "Idigicon", "Nihon Falcom", "Deep Silver", "Gamecock", "GameCock", "Xplosiv","Banpresto", "Sting",
                                            "Success Corporation", "Interactive Brains", "SCEI", "NIS America", "The Game Factory", 
                                            "Arc System Works","Atlas","Natsume", "Hudson Soft", "SouthPeak", "Xseed Games", "SNK Playmore", 
                                            "Now Production", "Take-Two Interactive", "Mastiff", "Empire Interactive", "Taito", "Bandai",
                                            "Buena Vista", "Tecmo", "Ignition", "Agetec", "FromSoftware"))
         )

```
```{r}
distinct_games <- pub_dev %>% select(name, developers, publishers) %>% distinct()
```

```{r}
games %>% group_by(publishers) %>% summarize(n=n()) %>% filter(n> 10)
```

```{r}
developers <- distinct_games %>% group_by(developers) %>% summarize(n=n()) 
developers %>% filter(n > 10)
```
```{r}
games %>% group_by(developers) %>% summarize(n=n()) %>% filter(n> 10)
```
```{r}
cleaned_developers <- developers %>%
  mutate(#dev_other = ifelse(n < 10, TRUE, FALSE),
         dev_Atlus = str_detect(developers, "Atlus"),
         dev_BioWare = str_detect(developers, "BioWare"),
         dev_Blizzard = str_detect(developers, "Blizzard"),
         dev_Activision = str_detect(developers, "Activision"),
         dev_Ubisoft = str_detect(developers, "Ubisoft"),
         dev_Rockstar = str_detect(developers, "Rockstar"),
         dev_1C = str_detect(developers, "1C"),
         dev_DICE = str_detect(developers, "DICE"),
         dev_Capcom = str_detect(developers, "Capcom"),
         dev_2K = str_detect(developers, "2K"),
         dev_343Industries = str_detect(developers, "343 Industries"),
         dev_CreativeAssembly = str_detect(developers, "Creative Assembly"),
         dev_FromSoftware = str_detect(developers, "FromSoftware"),
         dev_Vanguard = str_detect(developers, "Vanguard Games"),
         dev_Arkane = str_detect(developers, "Arkane"),
         dev_BandaiNamco = str_detect(developers, "Bandai Namco"),
         dev_Bethesda = str_detect(developers, "Bethesda"),
         dev_Bungie = str_detect(developers, "Bungie"),
         dev_Crytek = str_detect(developers, "Crytek"),
         dev_EA = str_detect(developers, "EA "),
         dev_Nintendo = str_detect(developers, "Nintendo"),
         dev_Ensemble = str_detect(developers, "Ensemble Studios"),
         dev_EpicGames = str_detect(developers, "Epic Games"),
         dev_Frontier = str_detect(developers, "Frontier Developments"),
         dev_Feral = str_detect(developers, "Feral Interactive"),
         dev_InfinityWard = str_detect(developers, "Infinity Ward"),
         dev_Insomniac = str_detect(developers, "Insomniac Games"),
         dev_JapanStudios = str_detect(developers, "Japan Studio"),
         dev_Klei = str_detect(developers, "Klei Entertainment"),
         dev_Konami = str_detect(developers, "Konami"),
         dev_LucasArts = str_detect(developers, "LucasArts"),
         dev_NaughtyDog = str_detect(developers, "Naughty Dog"),
         dev_Namco = str_detect(developers, "Namco"),
         dev_TellTale = str_detect(developers, "Telltale Games")) 

other_dev = cleaned_developers[ rowSums(cleaned_developers[3:36]) == 0,]

cleaned_developers <- cleaned_developers %>%
  mutate(dev_other = ifelse(developers %in% other_dev$developers, TRUE, FALSE)) %>%
  select(-n)

```


```{r}
publishers <- distinct_games %>% group_by(publishers) %>% summarize(n=n()) 
publishers %>% filter(n <10)
```
```{r}
clean_pubs <- publishers %>%
  mutate(#pub_other = ifelse(n<10, TRUE, FALSE),
         pub_Eidos = str_detect(publishers, "Eidos Interactive"),
         pub_EA = str_detect(publishers, "EA Games"),
         pub_DeepSilver = str_detect(publishers, "Deep Silver"),
         pub_ElectronicArts = str_detect(publishers, "Electronic Arts"),
         pub_Ubisoft = str_detect(publishers, "Ubisoft"),
         pub_Sega = str_detect(publishers, "Sega"),
         pub_Activision = str_detect(publishers, "Activision"),
         pub_SquareEnix = str_detect(publishers, "Square Enix"),
         pub_Devolver = str_detect(publishers, "Devolver Digital"),
         pub_Capcom = str_detect(publishers, "Capcom"),
         pub_Konami = str_detect(publishers, "Konami"),
         pub_BandaiNamco = str_detect(publishers, "Bandai Namco"),
         pub_Paradox = str_detect(publishers, "Paradox Interactive"),
         pub_Nintendo = str_detect(publishers, "Nintendo"),
         pub_Sony = str_detect(publishers, "Sony"),
         pub_koei = str_detect(publishers, "Koei"),
         pub_rockstar = str_detect(publishers, "Rockstar"),
         pub_THQ = str_detect(publishers, "THQ"),
         pub_2K = str_detect(publishers, "2K"),
         pub_D3 = str_detect(publishers, "D3"),
         pub_vivendi = str_detect(publishers, "Vivendi"),
         pub_majesco = str_detect(publishers, "Majesco"),
         pub_microsoft = str_detect(publishers, "Microsoft"),
         pub_505 = str_detect(publishers, "505 Games"),
         pub_Atari = str_detect(publishers, "Atari"),
         pub_Spike = str_detect(publishers, "Spike"),
         pub_RisingStar = str_detect(publishers, "Rising Star"),
         pub_Midway = str_detect(publishers, "Midway"),
         pub_Spike = str_detect(publishers, "LucasArts"),
         pub_WarnerBros = str_detect(publishers, "Warner Bros"),
         pub_Atlus = str_detect(publishers, "Atlus"),
         pub_Codemasters = str_detect(publishers, "Codemasters"),
         pub_Disney = str_detect(publishers, "Disney"),
         pub_Blizzard = str_detect(publishers, "Blizzard"),
         pub_Bethesda = str_detect(publishers, "Bethesda"),
         pub_Curve = str_detect(publishers, "Curve Digital"),
         pub_1C = str_detect(publishers, "1C"),
         pub_daedalic = str_detect(publishers, "Daedalic Entertainment"),
         pub_FocusHome = str_detect(publishers, "Focus Home Interactive"),
         dev_HumbleBumble = str_detect(publishers, "Humble Bumble"),
         dev_Kalypso = str_detect(publishers, "Kalypso Media"),
         pub_TellTale = str_detect(publishers, "Telltale Games"),
         dev_Team17 = str_detect(publishers, "Team17"),
         dev_Valve = str_detect(publishers, "Valve"),
         dev_Xbox = str_detect(publishers, "Xbox Game Studios"),
         dev_tinyBuild = str_detect(publishers, "tinyBuild"))
clean_pubs 
other_pubs <- clean_pubs[ rowSums(clean_pubs[3:47]) == 0,]

clean_pubs <- clean_pubs %>% 
  mutate(pub_other = ifelse(publishers %in% other_pubs$publishers, TRUE, FALSE),
         pub_EA = ifelse(publishers == "EU: IDEA GamesNA: Meridian4 Bohemia Interactive", FALSE, pub_EA),
         pub_other = ifelse(publishers == "EU: IDEA GamesNA: Meridian4 Bohemia Interactive", TRUE, pub_other)) %>%
  select(-n)

pub_dev1 <- pub_dev %>%
  left_join(cleaned_developers, by = "developers")

cleaned_pub_dev <- pub_dev1 %>%
  left_join(clean_pubs, by = "publishers")

export(cleaned_pub_dev, "~/Documents/DS-Masters/Capstone/GamerGate/DataVisualization/CurrentVisualization/Final_dev_pub.csv")
setdiff(games, pub_dev)

cleaned_pub_dev %>%
  select(-c(released_metacritic, playtime, ))
```

         
Computer Entertainment = 72 
Blank = 68
Studios = 30
Game Studios = 29
```{r}
publishers %>%
  mutate(pub_other = ifelse(n < 10, TRUE, FALSE),
         pub_Atlus = str_detect(publishers, "Atlus"),
         pub_BioWare = str_detect(publishers, "BioWare"),
         
         
         
         pub_Rockstar = str_detect(publishers, "Rockstar"),
         
         pub_DICE = str_detect(publishers, "DICE"),
         
         pub_2K = str_detect(publishers, "2K"),
         pub_343Industries = str_detect(publishers, "343 Industries"),
         pub_CreativeAssembly = str_detect(publishers, "Creative Assembly"),
         pub_FromSoftware = str_detect(publishers, "FromSoftware"),
         pub_Vanguard = str_detect(publishers, "Vanguard Games"),
         pub_Arkane = str_detect(publishers, "Arkane"),
         
         
         pub_Bungie = str_detect(publishers, "Bungie"),
         pub_Crytek = str_detect(publishers, "Crytek"),
         
         pub_Nintendo = str_detect(publishers, "Nintendo"),
         pub_Ensemble = str_detect(publishers, "Ensemble Studios"),
         pub_EpicGames = str_detect(publishers, "Epic Games"),
         pub_Frontier = str_detect(publishers, "Frontier Developments"),
         pub_Feral = str_detect(publishers, "Feral Interactive"),
         pub_InfinityWard = str_detect(publishers, "Infinity Ward"),
         pub_Insomniac = str_detect(publishers, "Insomniac Games"),
         pub_JapanStudios = str_detect(publishers, "Japan Studio"),
         pub_Klei = str_detect(publishers, "Klei Entertainment"),
         
         pub_LucasArts = str_detect(publishers, "LucasArts"),
         pub_NaughtyDog = str_detect(publishers, "Naughty Dog"),
         pub_Namco = str_detect(publishers, "Namco"),
         ) 
```
```{r}
export(developers, "/Users/willavanliew/Documents/DS-Masters/Capstone/developers.csv")
```

```{r}
developers %>%
  mutate(dev_Jaleco = str_detect(developers, "Jaleco"),
         dev_CreativeAssembly = str_detect(developers, "Creative Assembly"),
         dev_Frogwares = str_detect(developers, "Frogwares"),
         dev_Spiders = str_detect(developers, "Spiders"),
         dev_YoungHorses = str_detect(developers, "Young Horses"),
         dev_Monolith = str_detect(developers, "Monolith Productions"),
         dev_10tons = str_detect(developers, "10tons"),
         dev_other = ifelse(n < 10, TRUE, FALSE),
         developers = str_replace(developers, "Jaleco", ""),
         developers = str_replace(developers, "Creative Assembly", ""))


```

```{r}
games %>%
  mutate(pub_Nintendo = str_detect(publishers, "Nintendo"),
         pub_Ubisoft = str_detect(publishers, "Ubisoft"),
         pub_Sony = str_detect(publishers, "Sony"),
         pub_Activision = str_detect(publishers, "Activision"),
         pub_EA = str_detect(publishers, "EA"),
         pub_namco = str_detect(publishers, "Namco"),
         pub_konami = str_detect(publishers, "Konami"),
         pub_koei = str_detect(publishers, "Koei"),
         pub_sega = str_detect(publishers, "Sega"),
         pub_capcom = str_detect(publishers, "Capcom"),
         pub_rockstar = str_detect(publishers, "Rockstar"),
         pub_THQ = str_detect(publishers, "THQ"),
         pub_2K = str_detect(publishers, "2K"),
         pub_D3 = str_detect(publishers, "D3"),
         pub_vivendi = str_detect(publishers, "Vivendi"),
         pub_majesco = str_detect(publishers, "Majesco"),
         pub_microsoft = str_detect(publishers, "Microsoft"),
         pub_SquareEnix = str_detect(publishers, "SquareEnix"),
         pub_505 = str_detect(publishers, "505 Games"),
         pub_Atari = str_detect(publishers, "Atari"),
         pub_Spike = str_detect(publishers, "Spike"),
         pub_RisingStar = str_detect(publishers, "Rising Star"),
         pub_Midway = str_detect(publishers, "Midway"),
         pub_Spike = str_detect(publishers, "LucasArts"),
         pub_Eidos = str_detect(publishers, "Eidos"),
         pub_WarnerBros = str_detect(publishers, "Warner Bros"),
         pub_Atlus = str_detect(publishers, "Atlus"),
         pub_Codemasters = str_detect(publishers, "Codemasters"),
         pub_Disney = str_detect(publishers, "Disney"))
```

```{r}
convertToBinary <- function(data, columns) {
  # Subset the data with the specified columns
  subset_data <- data[, columns]
  
  # Convert NA values to 0 and non-NA values to 1
  binary_data <- ifelse(is.na(subset_data), 0, 1)
  
  # Replace the subset columns in the original data with the binary values
  data[, columns] <- binary_data
  
  # Return the modified data set
  return(data)
}
```

```{r}
convertToBinary <- function(data, columns) {
  # Subset the data with the specified columns
  subset_data <- data[, columns]
  
  # Convert NA values to 0 and non-NA values to 1
  binary_data <- ifelse(is.na(subset_data), 0, 1)
  
  # Replace the subset columns in the original data with the binary values
  data[, columns] <- binary_data
  
  # Return the modified data set
  return(data)
}
```

```{r}
ds <- cleaned_pub_dev %>% pivot_wider(names_from = "platform_name", values_from = "platform_name")
ds <- convertToBinary(ds, (95:140)) %>% distinct()


ds <- ds %>% pivot_wider(names_from = "gamemodes", values_from ="gamemodes")

ds <- convertToBinary(ds, (140:142))
export(ds, "~/Documents/DS-Masters/Capstone/GamerGate/DataVisualization/CurrentVisualization/Final_dev_pub.csv")

```

