---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(lubridate) 
```
```{r}
games <- read_csv("cleaned_games.csv")

unique(games$max_players)
```

```{r}
games <- games %>%
  select(-c(handheld, multiplatform, online_play, prev_licensed, sequel, re_release))
```
```{r}
games

```

```{r}
games_action <- games %>%
  filter(genre_action == TRUE)
games_strat <- games %>%
  filter(genre_strategy == TRUE)
games_race <- games %>%
  filter(genre_racing_driving == TRUE)
games_sports <- games %>%
  filter(genre_sports == TRUE)
games_sim <- games %>%
  filter(genre_simulation == TRUE)
games_adv <- games %>%
  filter(genre_adventure == TRUE)
games_rpg <- games %>%
  filter(genre_rpg == TRUE)
games_ed <- games %>%
  filter(genre_educational == TRUE)

games_action %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
games_strat %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
games_adv %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
games_ed %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```

```{r}
games_race %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```

```{r}
games_rpg %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
games_sim %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
games_sports %>%
  summarize(num_games = n(), avg_reviewscore = mean(review_score), med_review_score = median(review_score), avg_sales = mean(total_sales), total_total_sales = sum(total_sales))
```
```{r}
publish <- as.tibble(unique(games$publishers))

games <- games %>%
  mutate(pub_Nintendo = str_detect(publishers, "Nintendo"),
         pub_Ubisoft = str_detect(publishers, "Ubisoft"),
         pub_Sony = str_detect(publishers, "Sony"),
         pub_Activision = str_detect(publishers, "Activision"),
         pub_EA = str_detect(publishers, "EA"),
         pub_namco = str_detect(publishers, "Namco"),
         pub_konami = str_detect(publishers, "Konami"),
         pub_koei = str_detect(publishers, "Koei"),
         pub_sega = str_detect(publishers, "Sega"),
         pub_capcom = str_detect(publishers, "Capcom"),
         pub_ignition = str_detect(publishers, "Ignition"),
         pub_agetec = str_detect(publishers, "Agetec"),
         pub_fromsoftware = str_detect(publishers, "FromSoftware"),
         pub_rockstar = str_detect(publishers, "Rockstar"),
         pub_THQ = str_detect(publishers, "THQ"),
         pub_tecmo = str_detect(publishers, "Tecmo"),
         pub_2K = str_detect(publishers, "2K"),
         pub_crave = str_detect(publishers, "Crave"),
         pub_buenavista = str_detect(publishers, "Buena Vista"),
         pub_D3 = str_detect(publishers, "D3"),
         pub_vivendi = str_detect(publishers, "Vivendi"),
         pub_majesco = str_detect(publishers, "Majesco"),
         pub_microsoft = str_detect(publishers, "Microsoft"),
         pub_SquareEnix = str_detect(publishers, "SquareEnix"),
         pub_Empire = str_detect(publishers, "Empire Interactive"),
         pub_Zoo = str_detect(publishers, "ZOO Digital"),
         pub_Zoo = str_detect(publishers, "Zoo"),
         pub_Taito = str_detect(publishers, "Taito"),
         pub_505 = str_detect(publishers, "505 Games"),
         pub_Bandai = str_detect(publishers, "Bandai"),
         pub_Atari = str_detect(publishers, "Atari"),
         pub_Now = str_detect(publishers, "Now Production"),
         pub_TakeTwo = str_detect(publishers, "Take-Two Interactive"),
         pub_Spike = str_detect(publishers, "Spike"),
         pub_RisingStar = str_detect(publishers, "Rising Star"),
         pub_Mastiff = str_detect(publishers, "Mastiff"),
         pub_Midway = str_detect(publishers, "Midway"),
         pub_Spike = str_detect(publishers, "LucasArts"),
         pub_MarvelousInter = str_detect(publishers, "Marvelous Interactive"),
         pub_Natsume = str_detect(publishers, "Natsume"),
         pub_Eidos = str_detect(publishers, "Eidos"),
         pub_WarnerBros = str_detect(publishers, "Warner Bros"),
         pub_MarvelousEnter = str_detect(publishers, "Marvelous Entertainment"),
         pub_Xseed = str_detect(publishers, "Xseed Games"),
         pub_SNKPlaymore = str_detect(publishers, "SNK Playmore"),
         pub_Atlus = str_detect(publishers, "Atlus"),
         pub_HudsonSoft = str_detect(publishers, "Hudson Soft"),
         pub_SouthPeak = str_detect(publishers, "SouthPeak"),
         pub_DeepSilver = str_detect(publishers, "Deep Silver"),
          pub_Gamecock = str_detect(publishers, "Gamecock"),
         pub_Gamecock = str_detect(publishers, "GameCock"),
          pub_AdventureComp = str_detect(publishers, "The Adventure Company"),
          pub_Xplosiv = str_detect(publishers, "Xplosiv"),
          pub_Banpresto = str_detect(publishers, "Banpresto"),
          pub_Sting = str_detect(publishers, "Sting"),
          pub_SuccessCorp = str_detect(publishers, "Success Corporation"),
          pub_InteractiveBrains = str_detect(publishers, "Interactive Brains"),
         pub_SCEI = str_detect(publishers, "SCEI"),
         pub_NISAmerica = str_detect(publishers, "NIS America"),
         pub_GameFactory = str_detect(publishers, "The Game Factory"),
         pub_ArcSystem = str_detect(publishers, "Arc System Works"),
         pub_Atlas = str_detect(publishers, "Atlas"),
         pub_Marvelous = str_detect(publishers, "Marvelous"),
         pub_Codemasters = str_detect(publishers, "Codemasters"),
         pub_Idigicon = str_detect(publishers, "Idigicon"),
         pub_NihonFalcom = str_detect(publishers, "Nihon Falcom"),
         pub_MTVGames = str_detect(publishers, "MTV Games"),
         pub_Mindscape = str_detect(publishers, "Mindscape"),
         pub_Valve = str_detect(publishers, "Valve"),
         pub_DisneyIS = str_detect(publishers, "Disney Interactive Studios"),
         pub_ConspiracyEnter = str_detect(publishers, "Conspiracy Entertainment"),
         pub_TopWareInter = str_detect(publishers, "TopWare Interactive"),
         pub_PlayFirst = str_detect(publishers, "PlayFirst"),
         pub_Disney = str_detect(publishers, "Disney"),
         pub_VirginPlay = str_detect(publishers, "Virgin Play"),
        pub_V2 = str_detect(publishers, "V.2 Play,"),
        pub_Bethesda = str_detect(publishers, "Bethesda"),
        pub_RTL = str_detect(publishers, "RTL Games"),
        pub_NipponIchi = str_detect(publishers, "Nippon Ichi Software"),
        pub_Destineer = str_detect(publishers, "Destineer"),
        pub_FunboxMedia = str_detect(publishers, "Funbox Media"),
        pub_MumboJumbo = str_detect(publishers, "MumboJumbo"),
        pub_Sandlot = str_detect(publishers, "Sandlot Games"),
        pub_RedMile = str_detect(publishers, "Red Mile Entertainment"),
        pub_Oxygen = str_detect(publishers, "Oxygen Games"),
        pub_SierraEntert = str_detect(publishers, "Sierra Entertainment"),
        pub_NoiseFactory = str_detect(publishers, "Noise Factory"),
        pub_IdeaFactory = str_detect(publishers, "Idea Factory"),
        pub_DigitalEntertainmentPool = str_detect(publishers, "Digital Entertainment Pool"),
        pub_Gameloft = str_detect(publishers, "Gameloft"),
        pub_System3 = str_detect(publishers, "System 3"),
        pub_Aksys = str_detect(publishers, "Aksys"),
        pub_Brash = str_detect(publishers, "Brash"),
        pub_SNK = str_detect(publishers, "SNK")
         )

publishers <- games[,44:134]
```
```{r}
summary(publishers)
#9
#8: pub_Taito, pub_MarvelousInter
#7: pub_ignition, pub_tecmo, pub_Natsume
#6: pub_SouthPeak
#5: pub_buenavista, pub_Bandai
#4: pub_Empire, pub_HudsonSoft
#3: pub_crave, pub_Zoo, pub_MarvelousEnter, pub_Xseed, pub_SNK
#2: pub_agetec, pub_Mastiff, pub_DeepSilver
#1: pub_fromsoftware, pub_TakeTwo, pub_Now, pub_SNKPlaymore, pub_Gamecock, pub_Brash, pub_Aksys, pub_System3
pubs <- publishers %>%
  pivot_longer(0:91, names_to = "publisher", values_to = "count") %>%
  mutate(count = ifelse(count == TRUE, 1, 0))

pubcounts = pubs %>%
  group_by(publisher)%>%
  summarise(val = sum(count, na.rm = T))


pubcounts %>%
  filter(val == 1)


pubs %>%
  filter(publisher == "pub_2K", count == 1)
```

```{r}
games %>%
  filter(str_detect(publishers, "SCEI"))
```

